### ISSUE TITLE
Should the "Permission denied" error have its own custom message?

### ISSUE THREAD

**Issue by mate-code** [ctreffe/alfred#155]
When working on my script, I often had the `exp_data.csv` opened in Excel to check if the data collected was stored as intended.
But the file gets locked for writing when it's still opened in Excel, so I regularly got a "Permission denied" error, when I forgot to close it:

```
 Exception during experiment execution.
Traceback (most recent call last):
  File "d:\python\expra\venv\lib\site-packages\alfred3\localserver.py", line 120, in experiment
    script.exp_session.movement_manager.move(direction=move)
  File "d:\python\expra\venv\lib\site-packages\alfred3\ui_controller.py", line 426, in move
    self._move(direction=direction)
  File "d:\python\expra\venv\lib\site-packages\alfred3\ui_controller.py", line 312, in _move
    cpage.section._move(direction=direction, from_page=cpage, to_page=target_page)
  File "d:\python\expra\venv\lib\site-packages\alfred3\section.py", line 652, in _move
    to_page.section._enter()
  File "d:\python\expra\venv\lib\site-packages\alfred3\section.py", line 953, in _enter
    self.experiment.finish()
  File "d:\python\expra\venv\lib\site-packages\alfred3\experiment.py", line 1070, in finish
    self._export_data()
  File "d:\python\expra\venv\lib\site-packages\alfred3\experiment.py", line 1093, in _export_data
    exporter.export(DataManager.EXP_DATA)
  File "d:\python\expra\venv\lib\site-packages\alfred3\export.py", line 89, in export
    self.export_exp_data()
  File "d:\python\expra\venv\lib\site-packages\alfred3\export.py", line 162, in export_exp_data
    self._write(alldata, fieldnames, path)
  File "d:\python\expra\venv\lib\site-packages\alfred3\export.py", line 121, in _write
    self.write(data, fieldnames, path, self.delimiter)
  File "d:\python\expra\venv\lib\site-packages\alfred3\export.py", line 130, in write
    with open(path, "w", encoding="utf-8", newline="") as csvfile:
PermissionError: [Errno 13] Permission denied: 'D:\\Python\\Expra\\data\\exp_data.csv'
2021-11-19 16:48:48,150 - exp.default_id - INFO - experiment id=default_id - session id=sid-8bfdce3b90aa42c08104e3b7b75252a4 -
ExperimentSession.abort() called. Aborting session. Reason: error
```

I did understand why I got this error, because I got it various times before when working with other frameworks, but beginners are likely to not understand why their experiment threw an error at this exact time. So it might be beneficial to include a custom error message here that gives a hint that the `exp_data.csv` might still be opened in another program.

**Comment by jobrachem** [comment]
I think this is a good idea. We should simply catch the error in export.py and re-raise it with an informative error message. But we should not presume too much, only suggest a possible cause, namely the .csv file still being opened.

**Comment by ctreffe** [comment]
We discussed this and decided that the current message is sufficient, since this is a very rare scenario
