### ISSUE TITLE
Import Error in Sphinx Documentation

### ISSUE THREAD

**Issue by ctreffe** [ctreffe/alfred#265]
Currently, I am not able to build our documentation on alfredo3 from the newest repository version of alfred. I receive the following error message:

```bash
Running Sphinx v5.3.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/alfred/.virtualenvs/alfred3/lib/python3.7/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/alfred/alfred/docs/source/conf.py", line 93, in <module>
    from sphinx.ext.autodoc import ClassLevelDocumenter, InstanceAttributeDocumenter
ImportError: cannot import name 'InstanceAttributeDocumenter' from 'sphinx.ext.autodoc' (/home/alfred/.virtualenvs/alfred3/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py)
```

Since we did not change the Sphinx config, I assume that there might be a module version conflict. I updated sphinx, recommonmark, and the book theme to their current versions while updating alfred3. This might have caused the issue, but I am wondering whether there were any changes required in the conf.py for newer Sphinx versions? Researching the issue, I did not come up with any suggested solutions. What is the best course of action here? Trying to downgrade Sphinx?

**Comment by ctreffe** [comment]
As suspected, downgrading Sphinx to version 4.5.0 solved the issue. It seems that there was an incompability between the newer Sphinx core and some older extension versions.
