### ISSUE TITLE
Internal Server Error when quickly moving through experiment

### ISSUE THREAD

**Issue by jobrachem** [ctreffe/alfred#4]
When I click through the test experiment very quickly, an internal server error occurs:

```
[2019-02-25 16:57:35,190] ERROR in app: Exception on /experiment [POST]
Traceback (most recent call last):
File "/Users/jobrachem/.virtualenvs/alfred_lab_p3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/Users/jobrachem/.virtualenvs/alfred_lab_p3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/jobrachem/.virtualenvs/alfred_lab_p3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/jobrachem/.virtualenvs/alfred_lab_p3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/Users/jobrachem/.virtualenvs/alfred_lab_p3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/jobrachem/.virtualenvs/alfred_lab_p3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functionsrule.endpoint
File "/Users/jobrachem/ownCloud/praktikum_johannes/alfred_lab/src/alfred/helpmates/localserver.py", line 63, in experiment
script.experiment.userInterfaceController.moveForward()
File "/Users/jobrachem/ownCloud/praktikum_johannes/alfred_lab/src/alfred/uiController.py", line 292, in moveForward
super(QtWebKitUserInterfaceController, self).moveForward()
File "/Users/jobrachem/ownCloud/praktikum_johannes/alfred_lab/src/alfred/uiController.py", line 80, in moveForward
self._experiment.savingAgentController.runSavingAgents(1)
File "/Users/jobrachem/ownCloud/praktikum_johannes/alfred_lab/src/alfred/savingAgent.py", line 288, in runSavingAgents
_queue.put((priority, e, data, time.time(), level, self))
File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/queue.py", line 149, in put
self._put(item)
File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/queue.py", line 233, in _put
heappush(self.queue, item)
TypeError: '<' not supported between instances of 'Event' and 'Event'
127.0.0.1 - - [25/Feb/2019 16:57:35] "POST /experiment HTTP/1.1" 500 -
127.0.0.1 - - [25/Feb/2019 16:57:35] "GET /favicon.ico HTTP/1.1" 404 -
2019-02-25 16:57:35,294 - alfred.savingAgent - DEBUG - id=24118c - Running SavingAgent <LocalSavingAgent [path: /Users/jobrachem/ownCloud/praktikum_johannes/alfred_lab/src/save/2019-02-25T165706_data_24118c47f72e4d769b4ba35b60ae42d6.json]> succeeded
2019-02-25 16:57:35,297 - alfred.savingAgent - DEBUG - id=24118c - Running SavingAgent <LocalSavingAgent [path: /Users/jobrachem/ownCloud/praktikum_johannes/alfred_lab/src/save/2019-02-25T165706_data_24118c47f72e4d769b4ba35b60ae42d6.json]> succeeded
2019-02-25 16:57:35,298 - alfred.savingAgent - CRITICAL - MOST OUTER EXCEPTION IN SAVE WORKER!!!
```

**Comment by jobrachem** [comment]
More specifically, the error can be elicited by clicking "next", before the savingAgent finished it's work for the previous page.

**Comment by jobrachem** [comment]
Es scheint an einer Änderung der Vergleichsoperationen von Python 2.7 auf Python 3 zu liegen.

Der Fehler passiert hier:

```python
    def runSavingAgents(self, level, sync=False):

        priority = 1 if sync else 5
        e = threading.Event()
        data = self._experiment.dataManager.getData()
        data['save_time'] = time.time()
        _queue.put((priority, e, data, time.time(), level, self))
        if sync:
            e.wait()
```

In `_queue.put()` wird irgendwo `<` auf `e`, also auf `threading.Event` angewendet. Das passiert möglicherweise, weil der Input für `_queue.put()` ein Tupel ist: Zuerst werden die ersten beiden Elemente zweier Tupel verglichen, dann die nächsten beiden Elemente. Bei den ersten beiden klappt es, weil es die `priority` ist, und die ist integer. Für den Vergleich zweier Instanzen einer Klasse müssen besondere Methoden definiert sein:

>Instances of a class cannot be ordered with respect to other instances of the same class, or other types of object, unless the class defines enough of the methods `__lt__()`, `__le__()`, `__gt__()`, and `__ge__()` (in general, `__lt__()` and `__eq__()` are sufficient, if you want the conventional meanings of the comparison operators).

Quelle:
https://docs.python.org/3.1/library/stdtypes.html#comparisonshttps://docs.python.org/3.1/library/stdtypes.html#comparisons

Die Frage wäre jetzt: **Ist es erwünschtes Verhalten, dass in `_queue.put()` Instanzen von `threading.Event` verglichen werden?** In dem Fall wäre die Lösung möglicherweise, eine `CustomThreadingEvent` (vererbt von `threading.Event`) Klasse anzulegen und die Vergleichsmethoden zu definieren.

Relevante Stackoverflow Threads:
https://stackoverflow.com/questions/43481158/typeerror-not-supported-between-instances-of-state-and-state-python-3

https://stackoverflow.com/questions/53554199/heapq-push-typeerror-not-supported-between-instances

**Comment by jobrachem** [comment]
Ich konnte den Fehler durch eine Neuordnung der Elemente im Input von `_queue.put()` beheben:

```python
    def runSavingAgents(self, level, sync=False):

        priority = 1 if sync else 5
        e = threading.Event()                           # initialise empty threading event
        data = self._experiment.dataManager.getData()   # dictionary of the .json data file of current session
        data['save_time'] = time.time()                 # set data["save_time"] to current time
        _queue.put((priority, time.time(), level, e, data, self))
        if sync:
            e.wait()
```

Jetzt wird immer zuerst die Priority verglichen, dann die Zeit, dann das level. Der Fehler tritt nicht mehr auf. Bleibt die Frage, ob das Level tatsächlich erst **nach** der Zeit verglichen werden soll? Der Fall dürfte nämlich so gut wie nie eintreten, da die Zeit sich immer minimal zwischen zwei Vorgängen unterscheiden wird.
